services:
  - type: web
    name: zyntra-he-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/quarkus-app/quarkus-run.jar
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 1521
      - key: DB_NAME
        value: ORCL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        value: https://fiap-gs-front-2semestre.vercel.app,https://zyntra-he.vercel.app,http://localhost:5173,http://localhost:3000
